name: 'Kubernetes Pods Health Wait'
description: 'Waits for Github Actions started Kubernetes pods to all be in a healthy state.'
branding:
  icon: 'watch'
  color: 'blue'
inputs:
  max-retry-attempts:
    description: 'Maximum of times the check can be carried on.'
    required: false
    default: 10
  retry-delay:
    description: 'Time to wait (in seconds) before attempting the check after a failure.'
    required: false
    default: 30
  namespace:
    description: "Namespace to check"
    required: false
    default: 'default'
  all-namespaces:
    description: 'Set true to check all namespaces'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'src/index.js'
